### ISSUE TITLE
Version of tensorflow and keras

### ISSUE THREAD

**Issue by Hanguyen92** [al3xsh/rolling-element-bearing-fault-detection#1]
Hi al3xsh

Can you ask me for the version of TensorFlow and Keras? I am trying to run your source.
Thank you very much!

**Comment by al3xsh** [comment]
I used tensorflow 2.1 and keras 2.3.1.

I attach my conda environment file here for reference.

[my_environment.yml.txt](https://github.com/al3xsh/rolling-element-bearing-fault-detection/files/6020962/my_environment.yml.txt)

**Comment by Hanguyen92** [comment]
I got it and success, thank you
