### ISSUE TITLE
How to Run this code

### ISSUE THREAD

**Issue by pankaj251003** [al3xsh/rolling-element-bearing-fault-detection#2]
could you please tell how should i run this code

**Comment by al3xsh** [comment]
1) Download the data from https://csegroups.case.edu/bearingdatacenter/pages/welcome-case-western-reserve-university-bearing-data-center-website. I am using the normal baseline and the 48kHz drive-end fault data.
2) Download the repo
2) Install dependencies (I recommend using anaconda):
- tensorflow
- keras
- scikit-learn
- matplotlib
3) Run the training code for the network of your choice - in keras/<network>/train_<network>_<task>.py using the appropriate experiments file - e.g.

```
python train_rnn_wdcnn_loads.py @experiments/loads_scenario_1/base.txt
```

You can train one 1 load condition and test on the other 2, 2 load conditions and test on the other one, or all load conditions and test under varying signal to noise ratios.
